import AuthProvider from "./context/AuthProvider"
import { Toaster } from "@/components/ui/toaster"
import Navbar from "@/components/Navbar"
import './styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
      <body>
        {/* <Navbar></Navbar> */}
        {children}
        <Toaster></Toaster>
      </body>
      </AuthProvider>
    </html>
  )
}
